import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ac89cfe2-a425-41b4-b51a-facde9df1215/dunk-low-shoes-15mQNw.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "20 000 \u20bd",
    company: "f",
    color: "p",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/02d793e4-3ab7-41c4-bd43-cabe64fe6ae9/air-max-ishod-shoes-bBCBDn.png",
    title: "Nike Air Max Ishod",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "12 000 \u20bd",
    newPrice: "10 000 \u20bd",
    company: "m",
    color: "b",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/41da67aa-906c-4f21-a7aa-6dfbe8289570/dunk-low-shoes.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "16 000 \u20bd",
    company: "f",
    color: "b",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/air-max-plus-utility-shoes-HkwSWp.png",
    title: "Nike Air Max Plus Utility",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "25 000 \u20bd",
    company: "m",
    color: "b",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/49d6a0ba-d3c1-4d5f-b93f-b09af0c662ef/air-force-1-07-shoes-npDqNV.png",
    title: "Nike Air Force 1 '07",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "12 000 \u20bd",
    newPrice: "10 000 \u20bd",
    company: "m",
    color: "b",
    category: "Force",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/12efd972-ffaf-4be7-ace6-07b3d079bdd0/dunk-low-shoes-S9WbnS.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "16 000 \u20bd",
    newPrice: "14 000 \u20bd",
    company: "f",
    color: "r",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6f39b5d4-816f-4da7-bdb5-7bf5e85faa5f/dunk-low-older-shoes-4vvlMx.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "10 000 \u20bd",
    company: "k",
    color: "w",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/92a7af65-3cfe-4c0c-9223-68d6a77f4d09/dunk-low-younger-shoes-22lG4d.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "10 000 \u20bd",
    company: "k",
    color: "g",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/dce1a7fc-14f1-44bf-a65b-c3895f40738d/air-max-1-easyon-younger-shoes-ph2F4m.png",
    title: "Nike Air Max 1 EasyOn",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "8 000 \u20bd",
    company: "k",
    color: "g",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-shoes-HvZlfx.png",
    title: "Nike Air Force 1 '07",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "13 000 \u20bd",
    company: "m",
    color: "w",
    category: "Force",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/air-force-1-07-shoes-QMx6sn.png",
    title: "Nike Air Force 1 '07",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "13 000 \u20bd",
    company: "f",
    color: "w",
    category: "Force",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6de8217d-e9df-4680-8e0d-0bf16eb4829b/air-force-1-07-shoes-T7VsTC.png",
    title: "Nike Air Force 1 '07",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "13 000 \u20bd",
    company: "f",
    color: "w",
    category: "Force",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7dab0613-a91a-40f4-a463-031227cb3ad7/air-force-1-lv8-older-shoes-4rVWkp.png",
    title: "Nike Air Force 1 LV8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "10 000 \u20bd",
    company: "k",
    color: "bl",
    category: "Force",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/3e9f4fa4-1765-4c4d-b480-dd059ebf2f40/force-1-low-easyon-younger-shoes-mPTrnS.png",
    title: "Nike Force 1 Low EasyOn",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "10 000 \u20bd",
    newPrice: "8 000 \u20bd",
    company: "k",
    color: "w",
    category: "Force",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/fabffc20-6600-4860-8169-f5052cb7f2db/air-max-plus-older-shoes-NGV34z.png",
    title: "Nike Air Max Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "20 000 \u20bd",
    company: "m",
    color: "p",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/913d7b1a-c9ce-49dd-bf4e-99fa3516ae2d/air-max-plus-shoes-g0tRCQ.png",
    title: "Nike Air Max Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "20 000 \u20bd",
    company: "f",
    color: "b",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9b34192e-3fc7-428b-a986-51497ba15a72/air-max-plus-shoes-LWzXNs.png",
    title: "Nike Air Max Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "20 000 \u20bd",
    company: "m",
    color: "w",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/60961b55-71c8-4f94-bcb3-cf0009eb2ec5/air-max-plus-shoes-mzL6hp.png",
    title: "Nike Air Max Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "25 000 \u20bd",
    company: "m",
    color: "r",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/33c8c0e0-ad77-4b1c-ab67-2008a884f9e8/air-max-90-shoes-7c3thR.png",
    title: "Nike Air Max 90",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "17 000 \u20bd",
    newPrice: "15 000 \u20bd",
    company: "m",
    color: "bl",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/373610d3-ed0a-48c9-8918-51dd05bc8a96/air-max-plus-3-shoes-0kMMVb.png",
    title: "Nike Air Max Plus 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "24 000 \u20bd",
    company: "f",
    color: "w",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6515d3d8-10b5-41fa-b0d9-2b5b0bb4f53e/air-max-270-younger-shoes-DFVRKb.png",
    title: "Nike Air Max 270",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "10 000 \u20bd",
    company: "k",
    color: "bl",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5d5ee4d0-21be-4b09-aee9-bb179586b2b4/air-max-97-shoes-2J0s75.png",
    title: "Nike Air Max 97",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "16 000 \u20bd",
    company: "f",
    color: "g",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/90797510-9aec-4f21-aab7-fb87c705c61b/dunk-low-lx-nbhd-shoes-pwsh6x.png",
    title: "Nike Dunk Low LX NBHD",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "18 000 \u20bd",
    company: "f",
    color: "g",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/413b8122-99b0-46f6-ae3e-d778015ca339/max-90-cot-bootie-8MHJTf.png",
    title: "Nike Air Max 90 Cot",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "5 000 \u20bd",
    company: "k",
    color: "b",
    category: "Max",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d5a172a4-63de-4a03-b043-06649a0be10c/dunk-low-younger-shoes-C7x0z8.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "14 000 \u20bd",
    company: "k",
    color: "bl",
    category: "Dunk",
  },
  {
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6f39b5d4-816f-4da7-bdb5-7bf5e85faa5f/dunk-low-older-shoes-4vvlMx.png",
    title: "Nike Dunk Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "",
    newPrice: "12 000 \u20bd",
    company: "k",
    color: "w",
    category: "Dunk",
  },

];

export default data;